<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="coverlet.collector" />
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="NSubstitute" />
    <PackageReference Include="Microsoft.Extensions.Configuration" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\USTHBStudy.Application\USTHBStudy.Application.csproj" />
    <ProjectReference Include="..\..\src\USTHBStudy.Infrastructure\USTHBStudy.Infrastructure.csproj" />
    <ProjectReference Include="..\..\src\USTHBStudy.Domain\USTHBStudy.Domain.csproj" />
  </ItemGroup>

</Project>
